### ISSUE TITLE
Mardown Gedankenstrich -- or ---

### ISSUE THREAD

**Issue by astridx** [the-road-to-learn-react/the-road-to-react-german#10]
Should I use -- or --- ? 
See: https://rstudio.com/wp-content/uploads/2015/06/rmarkdown-german.pdf
(Gedankenstrich (engl. emdash): ---)

**Comment by rwieruch** [comment]
I use -- for the English version, but feel free to use --- for the German one if this is the right way to do it :)

**Comment by astridx** [comment]
Ok.
