### ISSUE TITLE
Frage zu Fragmenten

### ISSUE THREAD

**Issue by astridx** [the-road-to-learn-react/the-road-to-react-german#12]
ich tue mich etwas schwer mit der Übersetzung von 

"This is one way to have multiple top-level elements in your JSX. It doesn't turn out very readable, though, as it becomes verbose with the additional key attribute. Another solution is to use a React fragment:"

in der Datei

https://github.com/the-road-to-learn-react/the-road-to-react-german/blob/master/manuscript/react-modern/fragments.md

Wenn ich den Code

```
const Search = ({ search, onSearch }) => [
  <label key="1" htmlFor="search">
    Search:{' '}
  </label>,
  <input
    key="2"
    id="search"
    type="text"
    value={search}
    onChange={onSearch}
  />,
];
```

in

```
const Search = ({ search, onSearch }) => [
  <label  htmlFor="search">
    Search:{' '}
  </label>,
  <input
    id="search"
    type="text"
    value={search}
    onChange={onSearch}
  />,
];
```

ändere, also den key weg lasse, dann arbeitet die Beispielanwendung fehlerfrei. 

Habe ich da etwas falsch verstanden?

**Comment by rwieruch** [comment]
"Das ist eine Möglichkeit mehrere Elemente als Wurzelelemente im JSX zu haben. Es trägt aber nicht sonderlich der Lesbarkeit bei, da jedes Element mit einem `key` Attribut ausgestattet werden muss. Deswegen bieten React Fragmente eine weitere Möglichkeit:"

Man kann den key weglassen, genauso wie bei einer [Liste in React](https://www.robinwieruch.de/react-list-component). Es wird aber dann zu Komplikationen führen, sobald die Reihenfolge der Elemente dynamisch geaendert werden kann oder Element entfernt oder hinzugefuegt werden. Macht das Sinn?

**Comment by astridx** [comment]
Danke fürs Erklären. 
ich werde in der Übersetzung etwas hinzufügen. Zum Beispiel so:

> Normalerweise benötigt der von einer React-Komponente zurückgegebene JSX-Code ein umhüllendes Element. Mit Hilfe eines Arrays ist es möglich, mehrere Elemente nebeneinander zu rendern. Wenn wir mit einer Liste arbeiten, ist es unumgänglich, dass wir jedem Geschwisterelement einen Schlüssel `key` zuweisen. Ich zeige dir den Code exemplarisch. Wenn du ihn ausprobierst, wirst du auf den ersten Blick keinen Unterschied feststellen. Genauso wie bei einer [Liste](https://www.robinwieruch.de/react-list-component) ist es möglich, `key` wegzulassen. Sobald du ein Element entfernst oder hinzufügst, oder die Reihenfolge dynamisch änderst, wird du dann aber auf Problemen stoßen. Deshalb verwende `key` wie im nachfolgenden Code:

**Comment by rwieruch** [comment]
Der Text liest sich sehr schön @astridx :) Gute Arbeit!
