### ISSUE TITLE
`barebones JavaScript`

### ISSUE THREAD

**Issue by astridx** [the-road-to-learn-react/the-road-to-react-german#8]
Just to be sure

In the file

https://github.com/the-road-to-learn-react/the-road-to-react-german/blob/master/manuscript/react-modern/lists.md

you do not mean https://backbonejs.org/ 

with

`barebones JavaScript 
`
You mean it like it is in the example before the text `barebones JavaScript`, right?

**Comment by rwieruch** [comment]
`barebones` is right :)

**Comment by astridx** [comment]
Thanks, so line [98](https://github.com/the-road-to-learn-react/the-road-to-react-german/pull/7/files#diff-374d816bed2095373b3a61ae3a4b12b7R98) is correct.
